Repository WildCodeSchool/2023-03-JS-TLSE-P3-Serenity, pull requests merged in 2023-06, with the labels that each got.

#3 Import SQL
  backend/database.sql
Labels: Reviewed

#4 Fix DB
  backend/database.sql
Labels: Reviewed

#6 S01 us25 navbar
  backend/database.sql
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Navbar.jsx
  frontend/src/pages/Home.jsx
  frontend/src/styles/.gitkeep
  frontend/src/styles/Navbar.scss
Labels: Reviewed, Corrections done

#9 S01 us02 practician list modal
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/PracticianListModal.jsx
  frontend/src/pages/Home.jsx
  frontend/src/reset.css
  frontend/src/styles/PracticianListModal.scss
  package-lock.json
Labels: Reviewed

#10 S01 us25 navbar
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/contexts/StateContext.jsx
  frontend/src/pages/Home.jsx
  frontend/src/reset.css
  frontend/src/styles/Home.scss
  frontend/src/styles/Navbar.scss
  frontend/src/styles/PracticianListModal.scss
Labels: Reviewed, Corrections done

#11 S01 us02 practician list modal
  backend/src/controllers/practicianController.js
  backend/src/models/PracticianManager.js
  backend/src/models/index.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/PracticianListModal.jsx
  frontend/src/styles/Home.scss
  frontend/src/styles/Navbar.scss
  frontend/src/styles/PracticianListModal.scss
  frontend/src/styles/variable.scss
  package-lock.json
Labels: Reviewed, Corrections done

#16 S01 us02 practician list modal
  backend/src/controllers/ressourceCountController.js
  backend/src/models/index.js
  frontend/index.html
  frontend/src/components/PracticianListModal.jsx
  frontend/src/styles/Navbar.scss
  frontend/src/styles/PracticianListModal.scss
Labels: Reviewed

#17 S01 us01 admin authentication
  backend/.env.sample
  backend/database.sql
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/adminControllers.js
  backend/src/models/AdminManager.js
  backend/src/models/index.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/.env.sample
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Authentication.jsx
  frontend/src/contexts/AuthFunctionContext.jsx
  frontend/src/contexts/StateContext.jsx
  frontend/src/pages/AdminAuthentication.jsx
  frontend/src/pages/EspaceAdmin.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/PatientAuthentication.jsx
  frontend/src/styles/AdminAuthentication.scss
  frontend/src/styles/Authentication.scss
  frontend/src/styles/EspaceAdmin.scss
  frontend/src/styles/variable.scss
Labels: Corrections done

#18 S01 us25 navbar
  backend/database.sql
  frontend/index.html
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/assets/favicon.svg
  frontend/src/assets/logo.svg
  frontend/src/assets/serenity_logo.svg
  frontend/src/components/HeaderLocation.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/contexts/StateContext.jsx
  frontend/src/styles/HeaderLocation.scss
  frontend/src/styles/Navbar.scss
Labels: Reviewed

#20 Update .env.sample
  backend/.env.sample
Labels: Reviewed

#21 Update router.js
  backend/src/router.js
Labels: Reviewed

#22 S01 us05 update praticians
  backend/src/app.js
  backend/src/controllers/PraticianControllers.js
  backend/src/controllers/itemControllers.js
  backend/src/controllers/practicianController.js
  backend/src/models/ItemManager.js
  backend/src/models/PracticianManager.js
  backend/src/models/index.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Buttonadd.jsx
  frontend/src/components/PracticianListModal.jsx
  frontend/src/contexts/StateContext.jsx
  frontend/src/main.jsx
  frontend/src/styles/AdminAuthentication.scss
  frontend/src/styles/HeaderLocation.scss
  frontend/src/styles/Navbar.scss
  frontend/src/styles/PracticianListModal.scss
Labels: Reviewed, Corrections done

#24 S01 us25 navbar
  backend/database.sql
  backend/src/router.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/contexts/AuthFunctionContext.jsx
  frontend/src/contexts/StateContext.jsx
  frontend/src/styles/AdminAuthentication.scss
  frontend/src/styles/PracticianListModal.scss
Labels: Reviewed

#25 S01 us01 admin authentication
  backend/database.sql
  backend/src/controllers/adminControllers.js
  backend/src/models/AdminManager.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/package-lock.json
  frontend/src/components/Authentication.jsx
  frontend/src/components/PracticianListModal.jsx
  frontend/src/pages/AdminAuthentication.jsx
  frontend/src/pages/EspaceAdmin.jsx
  frontend/src/styles/Authentication.scss
Labels: Reviewed

#26 S02 us07 form admin
  backend/src/controllers/FormControllers.js
  backend/src/models/FormManager.js
  backend/src/models/index.js
  backend/src/router.js
  backend/src/services/.gitkeep
  frontend/.gitignore
  frontend/src/components/FormListModal.jsx
  frontend/src/pages/EspaceAdmin.jsx
  frontend/src/styles/EspaceAdmin.scss
  frontend/src/styles/FormListModal.scss
  frontend/src/styles/Navbar.scss
Labels: Reviewed, Corrections done
